# Generated by Django 4.1.6 on 2023-02-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_ayudante_duenio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ayudante',
        ),
        migrations.DeleteModel(
            name='Duenio',
        ),
    ]
